name: Build webdav-server for x86_64-unknown-linux-musl
on:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zhxiaogg/cargo-static-build@master
      - run:  cargo build --release --no-default-features --features=quota
      
      - name: Upload release
        uses: softprops/action-gh-release@v0.1.15
        with:
           tag_name: ${{ github.ref_name }}
           files: |
               target/release/webdav-server
