name: Build webdav-server for x86_64-unknown-linux-gnu
on:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install musl-tools
        run: |
          sudo apt-get update -y
          sudo apt-get install musl-tools -y
      - name: Install libpam and librpc
        run: |
          sudo apt-get install libpam0g-dev -y
          sudo apt-get install libntirpc-dev -y

      - name: Install rust
        run: |
          rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build  --release --all-features  --target x86_64-unknown-linux-gnu
      
      - name: Upload release
        uses: softprops/action-gh-release@v0.1.15
        with:
           tag_name: ${{ github.ref_name }}
           files: |
               target/release/webdav-server
