name: webdav-server cross build
permissions:
  contents: write
on:
  workflow_dispatch:
         
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:slim
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:
    - name: Install libpam and librpc
      run: |
          apt-get update -y
          apt-get install git -y
          apt-get install musl-tools -y
          apt-get install libpam0g-dev -y
          apt-get install libntirpc-dev -y
          
    - name: git clone webdav-server-rs
      run: |
        set -eux
        git clone   https://github.com/ruaue/webdav-server-rs
         
         
  
          
    - name: setup rust target
      run: |
        rustup target add x86_64-unknown-linux-musl
       
    - name: build rust project 
    #  working-directory:webdav-server-rs
      run: |
        set -eux
        pwd

        cd webdav-server-rs
        RUSTFLAGS="-C link-arg=-s" cargo build  --target x86_64-unknown-linux-musl --release  --all-features

        
    - name: ls 
      run: |
         pwd
         ls webdav-server-rs/target/release
    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
       tag_name: ${{ github.ref_name }}
       files: |
           webdav-server-rs/target/release/webdav-server
