name: webdav-server build and release
permissions:
  contents: write
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:alpine
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        apk add git
        git clone   https://github.com/ruaue/webdav-server-rs
         
         
    - name: install linux-pam 
      run: |
       apk add rpcgen 
       apk add rpcgen-dev
       apk add rpcgen-lib
       apk add portablexdr-dev        
       apk add linux-pam-dev
    - name: setup rust target
      run: |
        rustup taget  add x86_64-unknown-linux-musl
       
    - name: build rust project 
    #  working-directory:webdav-server-rs
      run: |
        set -eux
        pwd

        cd webdav-server-rs
        RUSTFLAGS="-C link-arg=-s" cargo build  --release --all-features 
        
    - name: ls 
      run: |
         pwd
         ls target/release
    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
       tag_name: ${{ github.ref_name }}
       files: |
           target/release/webdav-server
